version: '3.8'

services:
  # CTA Anomaly Detection API
  api:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: cta-anomaly-api-prod
    ports:
      - "8000:8000"
    volumes:
      - cta_data:/app/data
      - cta_models:/app/models
    environment:
      - PYTHONPATH=/app
      - ENVIRONMENT=production
    command: ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "8000", "--workers", "4"]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: always
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '0.5'

  # Streamlit Dashboard
  dashboard:
    build:
      context: ..
      dockerfile: docker/Dockerfile.dashboard
    container_name: cta-anomaly-dashboard-prod
    ports:
      - "8501:8501"
    volumes:
      - cta_data:/app/data
      - cta_models:/app/models
    environment:
      - PYTHONPATH=/app
      - API_BASE_URL=http://api:8000
      - ENVIRONMENT=production
    depends_on:
      api:
        condition: service_healthy
    restart: always
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.25'

  # Data Collection Service (runs periodically)
  data-collector:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: cta-data-collector-prod
    volumes:
      - cta_data:/app/data
    environment:
      - PYTHONPATH=/app
      - ENVIRONMENT=production
    command: ["python", "fetch_data.py"]
    restart: always
    depends_on:
      - api
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: '0.1'

  # Nginx reverse proxy (optional)
  nginx:
    image: nginx:alpine
    container_name: cta-nginx-prod
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api
      - dashboard
    restart: always

volumes:
  cta_data:
    driver: local
  cta_models:
    driver: local

networks:
  default:
    name: cta-anomaly-network-prod